on:
  push:
    branches:
      - master
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Read code
      id: read_file
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: "index.html.min"
        trim: true

    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://rest.iad-05.braze.com/preference_center/v1/c9f0b3d9-af6f-4825-a4e8-277ad8e43df6'
        method: 'PUT'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.API_KEY }}"}'
        data: '{ "name": "preference_center_name", "preference_center_title": "Diet Doctor", "preference_center_page_html": "${{ steps.read_file.outputs.content }}", "confirmation_page_html": "<h2>Preferences submitted successfully!</h2><p>Your Diet Doctor communication preferences have been saved. Thank you for updating your preferences.</p><a href="https://www.dietdoctor.com/" style="font-size: 1.6rem">Click here to return to https://www.dietdoctor.com/</a>" }'
